# --- #

# Default http port (by default 8000)
dev_addr: 0.0.0.0:9000

# --- #

# Project information
site_name: GHOST IN THE CLOUD # ğŸ‘ˆ Material for MkDocs
site_url: https://ndu69110.github.io/docs # ğŸ‘ˆ https://squidfunk.github.io/mkdocs-material/
site_author: 'ndu69110'
site_description: >-
  Write your documentation in Markdown and create a professional static site in
  minutes â€“ searchable, customizable, in 60+ languages, for all devices
copyright: Copyright &copy; 2025 | Built using MkDocs, Material for MkDocs and PyMdown Extensions <br> Hosted with â¤ï¸ in Github Pages # ğŸ‘ˆ copyright: Copyright &copy; 2016 - 2025 Martin Donath
docs_dir: docs/

# --- #

# Repository
repo_name: github.com/ndu69110 # ğŸ‘ˆ squidfunk/mkdocs-material
repo_url: https://github.com/ndu69110 # ğŸ‘ˆ https://github.com/squidfunk/mkdocs-material
theme:
  icon:
    repo: fontawesome/brands/github
edit_uri: /ndu69110/site/blob/main/docs # ğŸ‘ˆ If you set it to "" (empty string), the edit links are disabled.

# --- #

# Configuration
theme:
  font:
    text: Roboto
    code: Roboto Mono
  logo: logo/logo.webp
  favicon: logo/logo.webp # ğŸ‘ˆ assets/favicon.png
  name: material
  language: fr
  color_mode: dark
  custom_dir: material/overrides
  #logo: logo/logo.webp
  palette:
    - media: "(prefers-color-scheme)"
      ##toggle:
        ##icon: material/link
        ##name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      ##toggle:
        ##icon: material/toggle-switch
        ##name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  #!palette: 
    # Palette toggle for dark mode
    #!- scheme: slate
    ##  toggle:
    ##    icon: material/weather-sunny        # ğŸ‘ˆ default: material/brightness-7 
    ##    name: Switch to light mode
    # Palette toggle for light mode
    ##- scheme: default
    ##  toggle:
    ##    icon: material/weather-night        # ğŸ‘ˆ default: material/brightness-4
    ##    name: Switch to dark mode  
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select # ğŸ‘ˆ default: commented
    - content.footnote.tooltips # ğŸ‘ˆ default: commented
    - content.tabs.link # ğŸ‘ˆ default: commented
    - content.tooltips
    - header.autohide # ğŸ‘ˆ default: commented
    #- navigation.expand # ğŸ‘ˆ default: commented    # ğŸ‘ˆ commented on 11/29/2025

    - navigation.footer
    - navigation.indexes
    - navigation.instant # ğŸ‘ˆ default: commented
    - navigation.instant.prefetch # ğŸ‘ˆ default: commented
    - navigation.instant.progress # ğŸ‘ˆ default: commented
    - navigation.prune
      - navigation.sections   # ğŸ‘ˆ commented on 11/29/2025
    - navigation.tabs
    - navigation.tabs.sticky # ğŸ‘ˆ default: commented
      #- navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate # ğŸ‘ˆ default: commented
    - header.hide_repo_revision               # ğŸ‘ˆ empÃªche lâ€™affichage du numÃ©ro ou texte sous le nom
    - navigation.instant.preview
    - navigation.path
    - toc.sections
    - search.related

# --- #

# Plugins
plugins:
  - projects
  - optimize
  #- offline
  #- privacy
  - open-in-new-tab:
      add_icon: true
  - blog:
      archive: true
      archive_date_format: MMMM yyyy
      enabled: true                           # ğŸ‘ˆ if false: hide the blog
      blog_toc: true                          # ğŸ‘ˆ if false: hide the blog TOC
      post_date_format: full
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      post_url_format: "{categories}/{slug}"
      post_url_max_categories: 2
      post_readtime: true                     # ğŸ‘ˆ if false: hide the read time
      categories: true                        # ğŸ‘ˆ if false: hide the categories
      categories_name: Categories
      authors: true                           # ğŸ‘ˆ if false: hide the authors
      draft: true
      draft_if_future_date: true
      pagination_per_page: 5
  - search:
      enabled: true # ğŸ‘ˆ Added                # ğŸ‘ˆ if false: hide the search bar
      lang: fr # ğŸ‘ˆ Added
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      pipeline: # ğŸ‘ˆ Added
        - stemmer # ğŸ‘ˆ Added
        - stopWordFilter # ğŸ‘ˆ Added
        - trimmer # ğŸ‘ˆ Added
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - tags: # ğŸ‘ˆ added                           # ğŸ‘ˆ Material built-in plugin
      tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      tags_slugify_separator: _
      tags_slugify_format: "tag:{slug}"
      tags_sort_by: !!python/name:material.plugins.tags.tag_name_casefold
      tags_sort_reverse: true
      tags_name_property: tags
      tags_name_variable: tags
      listings_sort_by: !!python/name:material.plugins.tags.item_title
      listings_sort_reverse: false            # ğŸ‘ˆ if false: show the tags in the correct order
      tags_sort_by: !!python/name:material.plugins.tags.tag_name_casefold
      tags_sort_reverse: true
      #listings_directive: $tags              # ğŸ‘ˆ hide tags if not commmented

# --- #

# Hooks
hooks:
  - hooks/socialmedia.py
  - material/overrides/hooks/shortcodes.py
  - material/overrides/hooks/translations.py

# --- #

# Additional configuration
extra:
  consent:
    actions:
      - accept
      - reject
      - manage 
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: 'simple/github' # ğŸ‘ˆ fontawesome/brands/github
      link: 'https://github.com/ndu69110' # ğŸ‘ˆ https://github.com/squidfunk
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/nicolas-dupre-94b2a078/
      name: nicolas dupre on Linkedin
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/ndu69110
#    - icon: fontawesome/brands/coffee
#      link: https://buymeacoffee.com/ndu69
#      name: Buy me a coffee
#  footer:
#    <a href="https://buymeacoffee.com/ndu69" target="_blank">
#      â˜• Buy me a coffee
#    </a>
  generator: false # ğŸ‘ˆ if true : show auto footer "made with ..."

# --- #

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc: # ğŸ‘ˆ got it 
      permalink: "#" # ğŸ‘ˆ got it but not same value
      baselevel: 2
      separator: "_"
      title: SOMMAIRE                         # ğŸ‘ˆ TOC name
      permalink_title: Anchor link to this section for reference
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      options:
        custom_icons:
          - material/overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true # ğŸ‘ˆ got it 
      use_pygments: true
      pygments_lang_class: true # ğŸ‘ˆ got it 
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      line_spans: __span # ğŸ‘ˆ got it
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: ndu69110
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.blocks.caption
  - markdown.extensions.toc:
      permalink: true
  - markdown.extensions.md_in_html
  - markdown.extensions.meta
  - markdown.extensions.attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde
  - pymdownx.blocks.details
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.blocks.admonition:
      types:
        - note
        - abstract
        - info
        - tip
        - success
        - question
        - warning
        - failure
        - danger
        - bug
        - example
        - quote
        - download

# --- #

# Extra CSS
extra_css:
  - overrides/extra.css

extra_javascript:
  - javascripts/rename-code-title.js

# --- #

# Needed for the mkdocs-merge plugin.
# mkdocs-merge will merge the navigation of all sites in the central repository.
nav:
  - Accueil ğŸ  : index.md

  - "Qui suis-je ? ğŸ‘‹" : _whoami/whoami.md

  - Gestion du site âš™ï¸ : _gestionsite/gestionsite.md

  - Formations ğŸ“ :
    - 'Introduction': _projects/introduction/introduction.md
    - 'Sommaire': _projects/sommaire/sommaire.md
    - 'Formation Azure': 
      - 'Chaptitre 1': _projects/_formation-azure/azure-chap01.md
      - 'Chaptitre 2': _projects/_formation-azure/azure-chap02.md
      - 'Chaptitre 3': _projects/_formation-azure/azure-chap03.md
      - 'Chaptitre 4': _projects/_formation-azure/azure-chap04.md
      - 'Chaptitre 5': _projects/_formation-azure/azure-chap05.md
      - 'Chaptitre 6': _projects/_formation-azure/azure-chap06.md
      - 'Chaptitre 7': _projects/_formation-azure/azure-chap07.md
      - 'Chaptitre 8': _projects/_formation-azure/azure-chap08.md
      - 'Chaptitre 9': _projects/_formation-azure/azure-chap09.md
      - 'Chaptitre 10': _projects/_formation-azure/azure-chap10.md
      - 'Chaptitre 11': _projects/_formation-azure/azure-chap11.md
      - 'Chaptitre 12': _projects/_formation-azure/azure-chap12.md
      - 'Chaptitre 13': _projects/_formation-azure/azure-chap13.md
      - 'Chaptitre 14': _projects/_formation-azure/azure-chap14.md
    - 'Formation Azure Devops': 
      - 'Chaptitre 1': _projects/_formation-azure-devops/azure-devops-chap01.md
      - 'Chaptitre 2': _projects/_formation-azure-devops/azure-devops-chap02.md
      - 'Chaptitre 3': _projects/_formation-azure-devops/azure-devops-chap03.md
      - 'Chaptitre 4': _projects/_formation-azure-devops/azure-devops-chap04.md
      - 'Chaptitre 5': _projects/_formation-azure-devops/azure-devops-chap05.md
      - 'Chaptitre 6': _projects/_formation-azure-devops/azure-devops-chap06.md
      - 'Chaptitre 7': _projects/_formation-azure-devops/azure-devops-chap07.md
      - 'Chaptitre 8': _projects/_formation-azure-devops/azure-devops-chap08.md
      - 'Chaptitre 9': _projects/_formation-azure-devops/azure-devops-chap09.md   
    - 'Formation Bash': 
      - 'Chaptitre 1': _projects/_formation-bash/bash-chap01.md
      - 'Chaptitre 2': _projects/_formation-bash/bash-chap02.md
      - 'Chaptitre 3': _projects/_formation-bash/bash-chap03.md
      - 'Chaptitre 4': _projects/_formation-bash/bash-chap04.md
      - 'Chaptitre 5': _projects/_formation-bash/bash-chap05.md
      - 'Chaptitre 6': _projects/_formation-bash/bash-chap06.md
      - 'Chaptitre 7': _projects/_formation-bash/bash-chap07.md
      - 'Chaptitre 8': _projects/_formation-bash/bash-chap08.md
      - 'Chaptitre 9': _projects/_formation-bash/bash-chap09.md
      - 'Chaptitre 10': _projects/_formation-bash/bash-chap10.md
      - 'Chaptitre 11': _projects/_formation-bash/bash-chap11.md
      - 'Chaptitre 12': _projects/_formation-bash/bash-chap12.md
      - 'Chaptitre 13': _projects/_formation-bash/bash-chap13.md
    - 'Formation Docker': 
      - 'Chaptitre 1': _projects/_formation-docker/docker-chap01.md
      - 'Chaptitre 2': _projects/_formation-docker/docker-chap02.md
      - 'Chaptitre 3': _projects/_formation-docker/docker-chap03.md
      - 'Chaptitre 4': _projects/_formation-docker/docker-chap04.md
      - 'Chaptitre 5': _projects/_formation-docker/docker-chap05.md
      - 'Chaptitre 6': _projects/_formation-docker/docker-chap06.md
      - 'Chaptitre 7': _projects/_formation-docker/docker-chap07.md
      - 'Chaptitre 8': _projects/_formation-docker/docker-chap08.md
      - 'Chaptitre 9': _projects/_formation-docker/docker-chap09.md
      - 'Chaptitre 10': _projects/_formation-docker/docker-chap10.md
      - 'Chaptitre 11': _projects/_formation-docker/docker-chap11.md
      - 'Chaptitre 12': _projects/_formation-docker/docker-chap12.md
    - 'Formation Git': 
      - 'Chaptitre 1': _projects/_formation-git/git-chap01.md
      - 'Chaptitre 2': _projects/_formation-git/git-chap02.md
      - 'Chaptitre 3': _projects/_formation-git/git-chap03.md
      - 'Chaptitre 4': _projects/_formation-git/git-chap04.md
      - 'Chaptitre 5': _projects/_formation-git/git-chap05.md
      - 'Chaptitre 6': _projects/_formation-git/git-chap06.md
      - 'Chaptitre 7': _projects/_formation-git/git-chap07.md
      - 'Chaptitre 8': _projects/_formation-git/git-chap08.md
      - 'Chaptitre 9': _projects/_formation-git/git-chap09.md
    - 'Formation Github Actions': 
      - 'Chaptitre 1': _projects/_formation-github-actions/github-actions-chap01.md
      - 'Chaptitre 2': _projects/_formation-github-actions/github-actions-chap02.md
      - 'Chaptitre 3': _projects/_formation-github-actions/github-actions-chap03.md
      - 'Chaptitre 4': _projects/_formation-github-actions/github-actions-chap04.md
      - 'Chaptitre 5': _projects/_formation-github-actions/github-actions-chap05.md
      - 'Chaptitre 6': _projects/_formation-github-actions/github-actions-chap06.md
      - 'Chaptitre 7': _projects/_formation-github-actions/github-actions-chap07.md
      - 'Chaptitre 8': _projects/_formation-github-actions/github-actions-chap08.md
    - 'Formation Gitlab CI/CD': 
      - 'Chaptitre 1': _projects/_formation-gitlab-cicd/gitlab-cicd-chap01.md
      - 'Chaptitre 2': _projects/_formation-gitlab-cicd/gitlab-cicd-chap02.md
      - 'Chaptitre 3': _projects/_formation-gitlab-cicd/gitlab-cicd-chap03.md
      - 'Chaptitre 4': _projects/_formation-gitlab-cicd/gitlab-cicd-chap04.md
      - 'Chaptitre 5': _projects/_formation-gitlab-cicd/gitlab-cicd-chap05.md
      - 'Chaptitre 6': _projects/_formation-gitlab-cicd/gitlab-cicd-chap06.md
      - 'Chaptitre 7': _projects/_formation-gitlab-cicd/gitlab-cicd-chap07.md
    - 'Formation NGINX': 
      - 'Chaptitre 1': _projects/_formation-nginx/nginx-chap01.md
      - 'Chaptitre 2': _projects/_formation-nginx/nginx-chap02.md
      - 'Chaptitre 3': _projects/_formation-nginx/nginx-chap03.md
      - 'Chaptitre 4': _projects/_formation-nginx/nginx-chap04.md
      - 'Chaptitre 5': _projects/_formation-nginx/nginx-chap05.md
      - 'Chaptitre 6': _projects/_formation-nginx/nginx-chap06.md
      - 'Chaptitre 7': _projects/_formation-nginx/nginx-chap07.md
      - 'Chaptitre 8': _projects/_formation-nginx/nginx-chap08.md
      - 'Chaptitre 9': _projects/_formation-nginx/nginx-chap09.md
      - 'Chaptitre 10': _projects/_formation-nginx/nginx-chap10.md
      - 'Chaptitre 11': _projects/_formation-nginx/nginx-chap11.md
      - 'Chaptitre 12': _projects/_formation-nginx/nginx-chap12.md
      - 'Chaptitre 13': _projects/_formation-nginx/nginx-chap13.md
      - 'Chaptitre 14': _projects/_formation-nginx/nginx-chap14.md
      - 'Chaptitre 15': _projects/_formation-nginx/nginx-chap15.md
      - 'Chaptitre 16': _projects/_formation-nginx/nginx-chap16.md
      - 'Chaptitre 17': _projects/_formation-nginx/nginx-chap17.md

  - Blog ğŸ“‘ :
    - blog/index.md
    - blog/author/team.md

  - Tags ğŸ”— : tags.md          # this will point to the generated page

  - Contact âœ‰ï¸ : _contact/contact.md

  - "Soutenez mon projetddd ğŸš€": _buymeacoffee/buymeacoffee.md
